package com.example.bilingual.db.model.enums;

public enum QuestionType {
    SELECT_THE_REAL_ENGLISH_WORDS,
    LISTEN_AND_SELECT_ENGLISH_WORDS,
    TYPE_WHAT_YOU_HEAR,
    DESCRIBE_IMAGE,
    RECORD_SAYING_STATEMENT,
    RESPOND_IN_AT_LEAST_N_WORDS,
    HIGHLIGHT_THE_ANSWER,
    SELECT_THE_MAIN_IDEA,
    SELECT_THE_BEST_TITLE,
}
